version: 2

models:
- name: stg_interactions
  description: "Staging table for simulated interactions"
  columns:
    - name: interaction_id
      tests:
        - not_null
        - unique
    - name: participant
      tests:
        - not_null
    - name: date
      tests:
        - not_null